title: Ragnarok Origin Auto Patcher
logo: /assets/img/logo.png
description: Auto Patcher is an third party app for Ragnarok Origin translating KR language to English.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
