title: RO-ENPatcher v2 fix 2
logo: /assets/img/logo.png
description: ENPatcher is a third party app for Ragnarok Origin translating other language to English.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
