title: Ragnarok Origin ENPatcher
logo: /assets/img/logo.png
description: Auto Patcher is a third party app for Ragnarok Origin translating KR language to English.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
